MRMV2/Models/AddRecipeViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MRMV2.Models
{
    public class AddRecipeViewModel
    {


        public List<string> Measurement { get; set; }

        public List<string> Ingredient_Name { get; set; }

        public string applianceUsed { get; set; }

        [Required(ErrorMessage = "Recipe completion time is required!")]
        public string time { get; set; }

        public string Tags { get; set; }

        [Required]
        public string Instructions { get; set; }

        [Required]
        public string Description { get; set; }

        [Required(ErrorMessage = "A recipe name is required!")]
        public string recipeName { get; set; }

        public int recipeVisibility { get; set; }

        public string displayPictureLocation { get; set; }

    }
}

MRMV2/Models/Comments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MRMV2.Models
{
    public class Comments
    {
        public string commentID { get; set; }
        public string comment { get; set; }
        public string commentDate { get; set; }

        public Users getUser { get; set; }
        public Recipe Recipe { get; set; }
        //public int recipeID { get; set; }
    }

}

MRMV2/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.IO;
using Microsoft.AspNet.Identity;
using System.Drawing;
using Novacode;
using System.Web.UI.WebControls;
using MRMV2.Models;
using System.Collections;

namespace MRMV2.Controllers
{
    public class RecipesController : Controller
    {

        private rdbEntities db = new rdbEntities();
        AccountController ac = new AccountController();



        /// <summary>
        /// This method lets a user edit their recipe after creation. 
        /// It finds the recipe of the id passed in and passes all relevant information of that recipe to the view to auto fill fields with the original values provided to the recipe
        /// </summary>
        /// <param name="id">The id of the recipe to edit</param>
        /// <returns>Information about this recipe and the EditRecipe View</returns>
        public ActionResult EditRecipe(string id)
        {
            if (id == null)
                return RedirectToAction("Index", "Home");

            try
            {
                Session["pictureName"] = null;
                //Get Recipe information from database
                var rec = (from r in db.Recipes where r.Recipe_ID == id select r).ToList();
                var appliances = (from a in db.Appliances_Used where a.Recipe_Id == id select a).ToList();
                var photos = (from p in db.Pictures where p.Recipe_ID == id select p).ToList();
                var ingr = (from i in db.Ingredients where i.Recipe_ID == id select i).ToList();
                var tags = (from t in db.User_Defined_Tags where t.Recipe_ID == id select t).ToList();

                //If the recipe is found
                if (rec != null)
                    if (rec.Count > 0)
                    {
                        //If its a different user trying to edit someone elses recipe redirect to home
                        if (rec[0].User_ID != User.Identity.GetUserId())
                            return RedirectToAction("Index", "Home");
                        Session["editID"] = id;

                        //Create a new recipeinfo object to pass back to the view which will hold pointers to the 4 objects beneath it
                        EditPageModel recipeInfo = new EditPageModel();
                        List<Appliances_Used> applianceInfo = new List<Appliances_Used>();
                        List<Picture> photoInfo = new List<Picture>();
                        List<User_Defined_Tags> userTags = new List<User_Defined_Tags>();
                        List<Ingredients> ingredInfo = new List<Ingredients>();

                        //If there are photos for the recipe add them to an object
                        if (photos != null)
                        {
                            foreach (var photo in photos)
                                photoInfo.Add(new Picture() { Picture_Location = photo.Picture_Location, Picture_ID = photo.Picture_ID });

                            recipeInfo.getImages = photoInfo;
                        }


                        //If there are appliances for the recipe add them to an object
                        if (appliances != null)
                        {
                            foreach (var appl in appliances)
                                applianceInfo.Add(new Appliances_Used() { Appliance_Name = appl.Appliance_Name, Id = appl.Id });
                            recipeInfo.getAppliances = applianceInfo;
                        }


                        //If there are tags for the recipe add them to an object
                        if (tags != null)
                        {

                            foreach (var tag in tags)
                            {
                                userTags.Add(new User_Defined_Tags() { User_Defined_Tag = tag.User_Defined_Tag, Tag_ID = tag.Tag_ID });
                            }
                            recipeInfo.getTags = userTags;

                        }

                        //If there are ingredients for the recipe add them to an object
                        if (ingr != null)
                        {
                            foreach (var ing in ingr)
                                ingredInfo.Add(new Ingredients() { ingredientName = ing.Ingredient_Name, measurement = ing.Measurement, ingredientID = ing.Recipe_Ingredient_ID });
                            recipeInfo.getIngredients = ingredInfo;
                        }



                        //Add information to the recipe object
                        var a = rec[0].Cooking_Time;
                        recipeInfo.getRecipe.Cooking_Time = rec[0].Cooking_Time;
                        recipeInfo.Instructions = rec[0].Instructions;
                        recipeInfo.Description = rec[0].Recipe_Description;
                        recipeInfo.getRecipe.Recipe_Name = rec[0].Recipe_Name;
                        recipeInfo.getRecipe.Recipe_Visibility = rec[0].Recipe_Visibility;
                        recipeInfo.getRecipe.Recipe_ID = id;
                        Session["UploadingRecipeID"] = id;
                        recipeInfo.recipeVisibility = rec[0].Recipe_Visibility;

                        //Pass all of the recipe information to the view
                        return View(recipeInfo);

                    }
            }
            catch (Exception) { }
            return View("Error");
        }


        /// <summary>
        /// Edit Recipe method takes the model from the editRecipe view and makes changes to a recipe
        /// </summary>
        /// <param name="model">Recipe Information from editRecipe view</param>
        /// <returns>Landing page view</returns>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult EditRecipe(EditPageModel model)
        {

            var rid = Session["editID"] as string;
            //If there is no recipe id return to the landing page
            if (rid == null)
                return RedirectToAction("Index", "Home");
            var uid = User.Identity.GetUserId() ?? "";
            //Get recipe to edit.
            var rec = (from r in db.Recipes where r.Recipe_ID == rid && r.User_ID == uid select r).ToList();
            if (rec != null)
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                try
                {
                    //Set the recipe to edit
                    var editRecipe = rec.First();

                    //Edit details
                    editRecipe.Recipe_Name = model.recipeName;
                    editRecipe.Recipe_Search_Name = model.recipeName.Replace(" ", "_");
                    editRecipe.Recipe_Description = model.Description;
                    if (model.Description.Length > 200)
                        editRecipe.Recipe_Short_Description = model.Description.Substring(0, 200) + "...";
                    else
                        editRecipe.Recipe_Short_Description = model.Description;
                    if (model.recipeVisibility == 1 || model.recipeVisibility == 0)
                        editRecipe.Recipe_Visibility = model.recipeVisibility;
                    else
                        editRecipe.Recipe_Visibility = 0;

                    editRecipe.Instructions = model.Instructions;


                    editRecipe.Cooking_Time = model.time;
                    editRecipe.Cooking_Time_Search_Name = model.time.Replace(" ", "_");




                    var uploadedRecipeID = (string)Session["UploadingRecipeID"];
                    List<string> pictureName = new List<string>();
                    pictureName = (List<string>)Session["pictureName"];

                    while (uploadedRecipeID == "")
                        uploadedRecipeID = Session["UploadingRecipeID"] as string;

                    //Add any new pictures
                    if (pictureName != null)
                    {
                        if (pictureName.Count != 0)
                            for (int i = 0; i < pictureName.Count; i++)
                            {
                                try
                                {
                                    var a = Server.MapPath("~/temp/" + pictureName[i]);
                                    var b = Server.MapPath("~/RecipeImages/" + pictureName[i]);
                                    System.IO.File.Move(a, b);
                                }
                                catch (IOException)
                                {

                                }
                            }

                        if (pictureName.Count != 0)
                            editRecipe.Display_Picture_Location = "../../RecipeImages/" + pictureName[0];

                        if (pictureName.Count != 0)
                        {

                            for (int i = 0; i < pictureName.Count; i++)
                            {
                                editRecipe.Pictures.Add(new Picture() { Picture_Location = "../../RecipeImages/" + pictureName[i], Recipe_ID = uploadedRecipeID, Picture_ID = uploadedRecipeID + returnRandomID() });
                            }
                        }

                    }

                    //Remove old tags
                    //Add new tags
                    var tagsList = (List<string>)Session["tagsList"];

                    if (tagsList != null)
                    {

                        var tags = (from c in db.User_Defined_Tags where c.Recipe_ID == rid select c);
                        foreach (var q in tags)
                            db.User_Defined_Tags.Remove(q);

                        for (int i = 0; i < tagsList.Count; i++)
                        {

                            if (tagsList[i] != "")
                            {

MRMV2/Views/Recipes/Comments.cshtml
@{
    var isAdmin = @Html.Action("isAdmin", "Home") + "";
    var getUserID = @Html.Action("getUserID", "Account") + "";
    var signedIn = @Model.signedIn;
}







<style>



    .trashCan {
        width: 20px;
        position: absolute;
        right: 0px;
        top: 0px;
    }


    .ui-widget-content{
        background:none;
    }


</style>





<hr id="spaceit" />
<div id="likeSaveReport">@using (Html.BeginForm("deleteRecipe", "Recipes", FormMethod.Post, new { id = "deleteRec" })) { }@Html.ActionLink("Save this recipe", "saveRecipe", "Recipes", new { }, new { @id = "saveRec", @style = "float:right" })<img class="saveIcon" /></div>

<h1>Comments</h1>


<div id="commentsArea">

</div>

@*<div id="commentarea">



    @if (isAdmin == "False" && signedIn == "t")
    {
        for (int i = 0; i < @Model.getComments.Count; i++)
        {
            if (@getUserID == @Model.getComments[i].getUser.userID)
            {
                <div class="Comments">
                    <img class="trashCan" id="@Model.getComments[i].commentID" />
                    <div><img class="commentImg" src="@Model.getComments[i].getUser.userProfilePicture" /></div>
                    <b>@Model.getComments[i].getUser.userName</b>
                    <br />
                    <span>@Model.getComments[i].comment</span>
                    <br />
                </div>

            }
            else
            {
                <div class="Comments">
                    <div><img id="@Model.getComments[i].commentID" class="commentImg" src="@Model.getComments[i].getUser.userProfilePicture" /></div>
                    <b>@Model.getComments[i].getUser.userName</b>
                    <span>@Model.getComments[i].comment</span>
                    <a class="report" onclick="loadReport('@Model.getComments[i].commentID','comment' )">Report</a>
                </div>
            }
        }
    }
    else
    {
        for (int i = 0; i < Model.getComments.Count; i++)
        {
            <div class="Comments">
                <img class="commentImg" src="@Model.getComments[i].getUser.userProfilePicture" />
                <b>@Model.getComments[i].getUser.userName</b>
                <br />
                <span>@Model.getComments[i].comment</span>
                <a class="report"></a>
                <br />
            </div>
        }
    }


</div>


<div id="commentForm">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken();
        <textarea id="comment" placeholder="Add to this discussion" rows="3" disabled="disabled"></textarea>
        <input type="button" id="postMessage" value="Submit" disabled="disabled" />
    }
</div>*@





<script>

    //Convert hex values to rgb
    function hexToR(h) { return parseInt((cutHex(h)).substring(0, 2), 16) }
    function hexToG(h) { return parseInt((cutHex(h)).substring(2, 4), 16) }
    function hexToB(h) { return parseInt((cutHex(h)).substring(4, 6), 16) }
    function cutHex(h) { return (h.charAt(0) == "#") ? h.substring(1, 7) : h }


    var contrastBoxColorRaw = '@Html.Action("getContrastColor", "User")';
    var contrastBoxColor = contrastBoxColorRaw.split('!!!###');

    R = hexToR(contrastBoxColor[0]);
    G = hexToG(contrastBoxColor[0]);
    B = hexToB(contrastBoxColor[0]);

    //Get Trash Icon
    var getTrash = '@Html.Action("getTrash", "User")';

    //Get Text color
    var textColor = "@Html.Action("getTextColor", "User")";

    var colors = "rgba(" + R + "," + G + "," + B + "," + contrastBoxColor[1] + ") !important";



    var inputBoxColorRaw = "@Html.Action("getInputColor", "User")";
    var inputBoxColor = inputBoxColorRaw.split('!!!###');

    inputR = hexToR(inputBoxColor[0]);
    inputG = hexToG(inputBoxColor[0]);
    inputB = hexToB(inputBoxColor[0]);

    //Set the toast positioning to fixed
    $("#toast").parent().css("position", "fixed");

    var getUserID = "@Html.Action("getUserID", "Account")";
    var isAdmin = '@Html.Action("isAdmin", "Home")';
    var signedIn = '@Model.signedIn';


    //If the user is logged in but not an admin display the like/dislike button
    if (isAdmin == "False" && signedIn == "t") {
        if (getUserID != '@Model.Uploader.userID') {
            //If the recipe is liked show the unlike button otherwise show the like button
            if ('@Html.Action("isLiked", "Recipes")' == "True") {
                $("#likeSaveReport").prepend("<span id=\"recRep\" onclick=\"loadReport('@Model.getRecipe.Recipe_ID','recipe')\"><img  src=\"../../Icons/report.png\" />Report</span>");
                $("#likeSaveReport").prepend("<span id=\"UnlikeRec\" onclick=\"likeR('U')\"><img  src=\"../../Icons/whitebreak.png\" />Unlike</span>");

            }
            else {
                $("#likeSaveReport").prepend("<span id=\"recRep\" onclick=\"loadReport('@Model.getRecipe.Recipe_ID','recipe')\"><img  src=\"../../Icons/report.png\" />Report</span>");
                $("#likeSaveReport").prepend("<span id=\"likeRec\" onclick=\"likeR('L')\"><img  src=\"../../Icons/WhiteHeart.png\" />Like</span>");

            }


        }
        else {
            $("#deleteRec ").prepend("<span id='edit'>Edit</span><span id='deleteRecipe'>Delete</span>");
        }
        $("#comment, #postMessage ").prop("disabled", false);
    }

    $("#deleteRecipe").on("click", function () {


        if (confirm("Are you sure you want to delete this recipe?"))
            $("#deleteRec").submit();
    });


    //On like/unlike click
    function likeR(lod) {
        $.ajax({
            url: '/Recipes/like',
            data: { lod: lod },
            success: function () {
                if (lod == "L") {
                    $("#likeRec").remove();
                    $("#likeSaveReport").prepend("<span id=\"UnlikeRec\" onclick=\"likeR('U')\"><img src=\"../../Icons/whitebreak.png\" />Unlike</span>");
                }
                else {
                    $("#UnlikeRec").remove();
                    $("#likeSaveReport").prepend("<span id=\"likeRec\" onclick=\"likeR('L')\"><img  src=\"../../Icons/WhiteHeart.png\" />Like</span>");
                }

            }


        });
    }



    $(".Comments").css("background-color", colors);

    //On Comment submit
    $("#postMessage").on("click", function () {

        var comval = document.getElementById("comment").value;
        var u;
        var securityToken = "";
        if (comval != "") {
            securityToken = $('#commentForm input[name=__RequestVerificationToken]').val();
            u = '/Recipes/commentSubmit';


            $.ajax({
                type: "POST",
                url: u,
                data: {
                    __RequestVerificationToken: securityToken,
                    comment: comval
                },
                success: function (data) {
                    $("#commentarea").append("<div class=\"Comments\">" +
                        "<img class=\"trashCan\" src=\"" + getTrash + "\" id=\"" + data.returnList[3] + "\" />" +
                        "<img class=\"commentImg\" src=\"../../ProfilePicture/" + data.returnList[1] + "\" />" +
                        "<b>" + data.returnList[2] + "</b>" +
                        "<br /> " +
                        "<span>" + data.returnList[0] + "</span>" +
                        "<br />" +
                        "</div>");
                    document.getElementById("comment").value = "";
                    $(".Comments").css("background-color", colors);
                    //$(".report").css("color", textColor);
                }
            });
        }
        else {
            toast("Please enter a comment to upload", 2000);
        }

    });


    //Remove the comment
    $('body').on('click', '.trashCan', function () {

        $(this).parent().remove();
        var cid = $(this).prop("id")
        $.ajax({
            type: "POST",
            url: '/Recipes/removeComment',
            data: { commentid: cid },
        });
    })



    //Load a report for either comment or recipe
    function loadReport(reportIDin, reportType) {


        var a = '@Html.AntiForgeryToken()';
        if (reportType == "comment") {

            $("#recReportForm").html("<form>" + a + "<p><h1>Why are you reporting this comment?</h1></p><input type=\"checkbox\" value=\"Missing Content\" /> Missing Content<br /><br /><input type=\"checkbox\" value=\"Pointless Submission\" /> Pointless Submission" +
                    "<br /><br /><input type=\"checkbox\" value=\"Advertisement\" /> Advertisement<br /><br /><input type=\"checkbox\" value=\"Innapropriate Content\" /> Innapropriate Content<br /><br /><input type=\"checkbox\" value=\"Other\" id=\"Other\" /> Other" +
                    "<br /><br /></form>");
            type = reportType;
            commentID = reportIDin;

        }
        else if (reportType == "recipe") {
            $("#recReportForm").html("<form>" + a + "<p><h1>Why are you reporting this recipe?</h1></p><input type=\"checkbox\" value=\"Pointless Submission\" /> Pointless Submission" +
                "<br /><br /><input type=\"checkbox\" value=\"Incomplete Recipe\" /> Incomplete Recipe<br /><br /><input type=\"checkbox\" value=\"Advertisement\" /> Advertisement<br /><br /><input type=\"checkbox\" value=\"Innapropriate Content\" /> Innapropriate Content" +
                "<br /><br /><input type=\"checkbox\" value=\"Other\" id=\"Other\" /> Other<br /><br /></form>");
            type = reportType;
            reportID = reportIDin;

        }
        $("#recReportForm").dialog("open");
        var winHeight = $('body').height()
        var winWidth = $('body').width()
        var formWidth = $('#recReportForm').width()
        //Set the dialog css
        $("#recReportForm").closest(".ui-dialog").css("height", "640px");
        $("#recReportForm").closest(".ui-dialog").css("z-index", "501");
        $("#recReportForm").closest(".ui-dialog").css("left", (winWidth * .15) + "px");
        $("#recReportForm").closest(".ui-dialog").css("top", (winHeight * .15));
        $("#recReportForm").closest(".ui-dialog").css("padding", "0px");
        $("#recReportForm").closest(".ui-dialog").css("min-height", "640px");
        $("#recReportForm").siblings(".ui-dialog-buttonpane").css("position", "absolute");
        $("#recReportForm").siblings(".ui-dialog-buttonpane").css("width", "100%");
        $("#recReportForm").siblings(".ui-dialog-buttonpane").css("bottom", "0px");
        $("#recReportForm").siblings(".ui-dialog-titlebar").css("background", "transparent");
        

        $("#recReportForm").closest(".ui-resizable-handle").remove();

    }







    var x = $("#recipeInformationArea").height() / 1.2;
    $("#slide").css("max-height", x);
    $("#commentarea").css("height", window.innerHeight * .4 + "px");
    var reportID = "";
    var commentID = "";
    var type = "";


    //Create the report dialog
    $("#recReportForm").dialog({
        modal: true,
        width: 70 + "%",
        position: 'center',
        autoOpen: false,
        buttons: {
            "Submit Report": function () {
                var comval = "";

                $("#recReportForm input").each(function (key, element) { if (this.checked == true && element.value != "Other") comval += element.value + ", "; })
                if (document.getElementById("Other").checked == true)
                    comval += $("#OtherText").val() + ", ";
                var serviceURL = '/Recipes/Report';
                var securityToken = $('#recReportForm input[name=__RequestVerificationToken]').val();
                if (type == "comment")
                    var r = "Comment";
                else
                    r = "Recipe"
                if (comval != "")
                    $.ajax({
                        type: "POST",
                        url: serviceURL,
                        data: {
                            __RequestVerificationToken: securityToken,
                            commentID: commentID,
                            reasonForReport: comval,
                            rType: r,
                        },
                        success: function () {
                            $("#recReportForm input").each(function (key, element) { this.checked = false })
                            $("#OtherText").parent().remove()
                            $("#recReportForm").dialog("close");
                            toast("Your report has been recieved, The admins will review the report and make a decision. Thank you for taking time to clean up our website", 5000);
                        }


                    });
                else {
                    toast("A reason for reporting must be entered", 2000)
                }

            },
            Cancel: function () {

                $(this).dialog("close");
            }
        }
    });






    //On click of the edit link
    $("#edit").on("click", function () {
        window.location.href = '@Url.Action("EditRecipe", "Recipes", new {id = Model.getRecipe.Recipe_ID})';
    })

    

    //On checkbox check or uncheck remove or add the more information box on the report form
    $(document).on("change", "#Other", function () {
        if (this.checked) {
            $("#recReportForm").append("<div><textarea id=\"OtherText\" style=\" border: 1px solid "+textColor+"\" draggable=\"false\"> </textarea>If Other Please Specify</div>");

        }
        else
            $("#recReportForm div").remove();
    });


</script>

MRMV2/Views/Recipes/DisplayPicture.cshtml
    <div id="slide" class="cycle-slideshow"
         data-cycle-fx="fadeout"
         data-cycle-pause-on-hover=true>
        @for (int i = 0; i < Model.getImages.Count; i++)

        {<img src="@Model.getImages[i].Picture_Location" />}
        <div id="progress"></div>

    </div>
    

MRMV2/Views/Recipes/Information.cshtml
This Recipe Was Uploaded by the user : <span id="uploaderProfile" onclick="window.location.href='@Url.Action("Profile", "User", new {id = @Model.Uploader.userID})';">@Model.Uploader.userName <img id="uploaderImage" src="../../ProfilePicture/@Model.Uploader.userProfilePicture" /></span>
<div class="description">
    <h2>Description</h2>
    <textarea disabled="disabled">@Model.getRecipe.Recipe_Description</textarea><br>
</div>

<div id="ing">
    <br />
    <h2>Ingredients</h2>
    <ul>

        @for (int i = 1; i < @Model.getIngredients.Count + 1; i++)
        {

            <li>
                @Model.getIngredients[i - 1].measurement @Model.getIngredients[i - 1].measuringVessel @Model.getIngredients[i - 1].ingredientName
            </li>


        }

    </ul>



</div>
<br />
<h2>Instructions</h2>
<div id="instr">
    <textarea disabled="disabled">@Model.getRecipe.Instructions</textarea>




</div>
<div id="meth">
    @if (@Model.getAppliances.Count > 0)
    {
        <h2>Tools Used in this recipe.</h2>
        <ul>

            @for (int i = 0; i < @Model.getAppliances.Count; i++)
            {
                <li>@Model.getAppliances[i].Appliance_Name</li>
            }
        </ul>
    }
    else
    {

        <span>There were no tools used in the recipe.</span>
        <br />
    }
    <br />


    Cooking Time : @Model.getRecipe.Cooking_Time
</div>
<div id="tagsList">
    @if (@Model.getTags.Count > 0)
    {
        <ul>
            @for (int i = 0; i < @Model.getTags.Count; i++)
            {

                <li>
                    @Html.ActionLink((string)@Model.getTags[i].User_Defined_Tag, "Search", "Home", new { id = "recipeTags", term = @Model.getTags[i].User_Defined_Tag_Search }, new { @class = "navbar-brand" })
                </li>

            }
        </ul>
    }
    else
    {
        <br />
        <span>There were no tags given to this recipe.</span>
    }
</div>

<div id="recReportForm">


</div>